// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int countLarger = 0;
		int countsmaller = 0;
		for (int i = 0; i < N; i++){
			double randomNum = Math.random();
			if (randomNum > 0.5) {
				countLarger++;
			} else {
				countsmaller++;
			}
		}
		System.out.println("> 0.5:  " + countLarger + " times");
		System.out.println("<= 0.5: " + countsmaller + " times");
		if (countLarger > 0 && countsmaller > 0) {
			System.out.println("Ratio:  " + ((double) countLarger / countsmaller));
		}
	}
}
